### PR TITLE
Deprecated typealias Future

### PR DESCRIPTION
**Pull request by fabianfett**
- deprecated typealias Future
- removed all uses of public Future

will make transition in 5.0 easier.

### CODE REVIEW

**Comment by adam-fowler** [comment]
You didn't remove the Future<> usage in MetaDataService.

**Comment by adam-fowler** [comment]
You'll also need to do a similar PR for aws-sdk-swift as all the operation functions return a Future<>

**Comment by fabianfett** [comment]
https://github.com/swift-aws/aws-sdk-swift/pull/224

**Comment by adam-fowler** [comment]
I was just thinking merging this before we merge in async-http-client might make life difficult.

**Comment by adam-fowler** [comment]
> I was just thinking merging this before we merge in async-http-client might make life difficult. Otherwise everything looks good

Actually just merge it. I'll deal with the merge

**Pull request merged**
