### PR TITLE
Migrate package to Swift 4, remove support for Swift 3

### PR DESCRIPTION
**Pull request by Yasumoto**
This also modifies the package dependencies to use a slightly upgraded `HypertextApplicationLanguage`, but we can remove that if https://github.com/noppoMan/HypertextApplicationLanguage/pull/1 gets merged.

### CODE REVIEW

**Comment by Yasumoto** [comment]
@noppoMan How do you feel about bumping the version of Swift to 4.1? I think there are a few good improvements here, and we'll need it for #28 and #15 🙏

**Comment by jonnymacs** [comment]
@Yasumoto lgtm. I think Yuki was working on this for the parent sdk as well.

@noppoMan i will go ahead and merge this tomorrow morning if no objections

https://github.com/noppoMan/aws-sdk-swift/pull/75

**Comment by Yasumoto** [comment]
Sweet! Sounds like I could lend a hand on some build issue there, I’ll take a look tomorrow (I’m in Dublin, so it’s UTC for me) 👍

**Comment by jonnymacs** [comment]
@Yasumoto ok, what comes to mind is whether this warrants a version bump... since there is impact on the parent sdk, which still claims support for 3.x

Perhaps we should update the parent first?

**Pull request merged**
