### PR TITLE
GitHub Actions (with Container syntax)

### PR DESCRIPTION
**Pull request by fabianfett**
- builds on pr
- tests swift on linux versions with matrix builds
- uploads codecov from linux as well (> 5.1.2)
- uses linux auto test discovery (> 5.1.2)

### CODE REVIEW

**Comment by adam-fowler** [comment]
Fabian are you struggling to get the CODECOV_TOKEN? It might be due to the fact this is a pull request from another repository. If you could access secrets in this repository be creating a pull request that wouldn’t make the secrets very secret.

**Comment by fabianfett** [comment]
Will give it a new try tomorrow morning. Thanks for inviting me into swift-aws.

**Comment by adam-fowler** [comment]
> Will give it a new try tomorrow morning. Thanks for inviting me into swift-aws.

You obviously care about the quality of this library and have some good ideas about direction. It was a no-brainer really. 

Now you are a member you can move this branch into swift-aws/aws-sdk-swift-core and get access to the CODECOV_TOKEN secret.

**Comment by fabianfett** [comment]
Further work in #147

**Pull request closed without merging**
