### PR TITLE
Allow users to specify custom timeouts for requests

### PR DESCRIPTION
**Pull request by mrabiciu**
On a slow or busy network 5 seconds is sometimes not enough. 
This diff adds a custom timeout parameter to all the send methods and defaults to the previous 5 second timeout.

### CODE REVIEW

**Comment by adam-fowler** [comment]
We are looking to allow the user to provide their own HTTPClient in the near future #165. You would be able to control the timeout's from there once that work is in place. So I'm not sure this is necessary.

**Comment by fabianfett** [comment]
Hi @mrabiciu, thanks so much for your contribution. It's always exciting to see new developers getting involved with this project!

I think that your intent is certainly of relevance and that we should do something in this area. 

As @adam-fowler has pointed out our current thinking focuses (we are currently in the planning/ beginning of version 5.0) on giving the user the option to create the [AsyncHTTPClient](https://github.com/swift-server/async-http-client) themselves and injecting the client into the AWSClient. (See #165) The AWSClient itself could then be used to initialise the service facade (See swift-aws/aws-sdk-swift#231). With this approach you could configure the timeout interval on the AsyncHTTPClient and the value would be valid for all calls.

While your approach would introduce some "clutter" to the API, I can also see the point that changing the timeout interval could be necessary on a per call basis. Using another AWSClient with a separate AsyncHTTPClient can not be in our interest, since it would limit connection pooling. 

In the end I think, you are right and we should accept your change (I think i'm in favor, for the same reasons I proposed #172).

Would you be okay, if we put it on the list for 5.0? While it is not a breaking API change, I'd be in favor if we roll this out with a major release.

Does this sound okay to you?

**Comment by adam-fowler** [comment]
Hi @mrabiciu yes thanks for your PR. 

@fabianfett I'm not convinced yet of the need for this. Is there a valid use case for setting the timeout on a call by call basis? This would be more clutter and we already have other PR/Issues suggesting additional parameters to the send() calls https://github.com/swift-aws/aws-sdk-swift/issues/231.

Also this PR is only the change to aws-sdk-swift-core. The timeout parameter would have to be passed to all the api calls in aws-sdk-swift. So every call would look like
```
let future = try s3.putObject(request, timeout: .seconds(20))
```

Another possibility is we store the timeout in the `ServiceConfig` from https://github.com/swift-aws/aws-sdk-swift/issues/231. 

Lets wait until the HTTPClient provider  and possibly the ServiceConfig work is complete and re-visit this then. 

@mrabiciu what are your thoughts?

**Comment by adam-fowler** [comment]
@mrabiciu #328

**Comment by adam-fowler** [comment]
This is now possible using by creating a copy of the service with a new time out value using `AWSService.timingOut(after:)`. Code would work as follows 
```
s3.timingOut(after: .seconds(60)).getObject(bucket: "mybucket", key: "mykey")
```
therefore I am closing this

**Pull request closed without merging**
